# Classifier Evaluation

## Task 1: Hold-Out

Implement the Hold-Out method in Python. Your function should accept a list of arbitrary elements and a parameter `training_set_ratio` (e.g. 0.8).
The function should return a training set and a testing set as specified by the `training_set_ratio`.

Note: Normally, we would use existing implementations (see below). 

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
x = [1, 2, 3, 4 , 5, 6, 7, 8, 9, 10]
train_test_split(x, train_size=.8)

[[5, 3, 9, 10, 7, 1, 2, 4], [8, 6]]

## Task 2: $k$-fold Cross-Validation

Below, you see how you can use $k$-fold CV in sklearn.

In [4]:
x = [1, 2, 3, 4 , 5, 6, 7, 8, 9, 10]

In [5]:
from sklearn.model_selection import KFold
splits = KFold(3, shuffle=False)
for i, (train_index, test_index) in enumerate(splits.split(x)):
    print(train_index, test_index)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


Now, implement the $k$-fold splitting for cross-validation in Python. 

Note: This is rather a Python exercise.

In [16]:
import numpy as np
def cv(data, k):
    # TODO
    result = {}
    lenf = len(data)
    np.random.shuffle(data)
    for i in range(k):
        result[i] = [data[int(((i)/k)*lenf):int(((i+1)/k)*lenf)], []]
        result[i][1] = [x for x in data if x not in result[i][0]]
    return result

print(cv(x, 3))


{0: [[4, 10, 3], [8, 1, 6, 7, 2, 9, 5]], 1: [[8, 1, 6], [4, 10, 3, 7, 2, 9, 5]], 2: [[7, 2, 9, 5], [4, 10, 3, 8, 1, 6]]}


In [7]:
#10
"""
1a)
to calculate Err*(h) you would need the real y label, which is unknown. Otherwise, why make an AI for it lol
1b)
Acc = right_guess/total
miss = wrong_guess/total = 1 - right_guess/total
1c)
Since the model is trained on D, the missclassification rate is valid for D. It could be overfit and therefore valid on ONLY D
1d)
!example bank: with the missclassification rate x and the number of total instances, you can calculate an estimation for the number of missclassifications.
These in turn all have a certain cost associated with it. Then the bank needs to decide, based on their internal number and costs, which model ends up being cheaper.

2a)
In the Holdout validation the input data is split into 2 sets with a certain percentage of the total data. Then the model is trained on one of those partial sets and validated on the other.
In the k-fold cross validation the input data is split into k sets with about equal size. Then the model is trained k times on all but 1 of those partial sets with the set that's being left out, always being unique.
The unique set is then used for validation and eventually the results of all k models are being averaged.
~basically having many sets and using every data point for training and testing while holdout, doesn't cross them.
2b)
while k-fold uses every data point for training and testing at some point, bootstrapping uses random data points of the input data multiple times, which generally results in a real subset.
2c)
yes, splitting and validation methods are independent from any performance measures.

3a)
Y+ = 3+7 = 10 # real plus
Y- = 1+9 = 10 # real minus
3b)
Prediction, isReal
Positive, True = 3 # TP
Positive, False = 1 # FP
Negative, False = 7 # FN
Negative, True = 9 # TN
3c)
Acc = (3+9)/(3+7+1+9) = 12/20
macro avg Precision: TP/2(TP+FP) + TN/2(TN+FN) = (3/4 + 9/16)/2 = 0.66
macro avg Recall: TP/2(TP+FN) + TN/2(TN+FP) = (3/11 + 9/10)/2 = 0.59
4a)
                ^y
            True False
y   True    5    4      TP, FN
    False   3    5      FP, TN
4b)
Pos: Prec = TP/(TP+FP) = 5/8
    Recall = TP/(TP+FN) = 5/9
Neg: Prec = TN/(TN+FN) = 5/9
    Recall = TN/(TN+FP) = 5/8
4c)
F1 = 2TP/(2TP+FN+FP) = 10/(10+4+3) = 10/17

5a)
D = Predicted -> 1:85, 2:22, 3:13
5b)
trivial = majority -> class 1
random? well, random 1/3 for each class
5c)
TP2 = 9
FP2 = 3+10
FN2 = 1+0
TN2 = 4+3+80+10 = 97
5d)
TP1 = 4
FP1 = 1+80
FN1 = 3+3
TN1 = 9+0+10+10 = 29

TP3 = 10
FP3 = 3+0
FN3 = 80+10
TN3 = 4+3+1+9 = 17

micro avg Precision = (4+9+10)/(4+9+10 + 13+81+3) = 0.19
micro avg Recall = (4+9+10)/(4+9+10 + 1+6+90) = 0.19

macro avg Precision = (4/85 + 9/22 + 10/13)/3 = 0.41
macro avg Recall = (4/10 + 9/10 + 10/90)/3 = 0.47
"""

"\n1a)\nto calculate Err*(h) you would need the real y label, which is unknown. Otherwise, why make an AI for it lol\n1b)\nAcc = right_guess/total\nmiss = wrong_guess/total = 1 - right_guess/total\n1c)\nSince the model is trained on D, the missclassification rate is valid for D. It could be overfit and therefore valid on ONLY D\n1d)\n!example bank: with the missclassification rate x and the number of total instances, you can calculate an estimation for the number of missclassifications.\nThese in turn all have a certain cost associated with it. Then the bank needs to decide, based on their internal number and costs, which model ends up being cheaper.\n\n2a)\nIn the Holdout validation the input data is split into 2 sets with a certain percentage of the total data. Then the model is trained on one of those partial sets and validated on the other.\nIn the k-fold cross validation the input data is split into k sets with about equal size. Then the model is trained k times on all but 1 of th